#
# Dockerfile for a AceD Coin masternode
# usage: docker run notatestuser/masternode-aced:latest
#
# how to work with the container
#
# 1) build the container (checkout desired git revision first)
# docker build -t "notatestuser/masternode-aced:latest" -f docker/ACED/Dockerfile_ACED .
#
# 2) start the container
# docker run -p ${NODE_PORT}:${NODE_PORT} -v $(PWD)/data:/opt/aced/data "notatestuser/masternode-aced:latest"
#
# 3) start the container interactively
# docker run --interactive --tty --entrypoint=/bin/bash "notatestuser/masternode-aced:latest"

FROM         ubuntu:xenial
MAINTAINER   Rafael Dias  <github.com/devrdias>

ENV CONTAINER_USER   masternode
ENV PROJECT          aced
ENV GIT_URL          git://https://github.com/Acedcoin/AceD/=
ENV SVC_VERSION      1.8
ENV HOME_DIR         /opt/aced
ENV DATA_DIR         /opt/aced/data
ENV NODE_PORT        70211
ENV REFRESHED_AT     2018-01-11

# add unprivileged user
RUN adduser --shell /bin/bash --disabled-password \
    --disabled-login --gecos '' ${CONTAINER_USER}

# install packages
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y software-properties-common python-software-properties && \
    add-apt-repository ppa:aced/ppa && \
    apt-get update && \
    apt-get install -y acedd=$SVC_VERSION && \
    apt-get purge -y python-software-properties && \
    apt -y autoremove && \
    rm -rf /var/lib/apt/*

# init home and data dirs
RUN mkdir -p ${HOME_DIR} && \
    mkdir -p ${DATA_DIR} && \
    chown -R ${CONTAINER_USER} ${HOME_DIR} && \
    chown -R ${CONTAINER_USER} ${DATA_DIR}

# EXPOSE the masternode port
EXPOSE ${NODE_PORT}

USER ${CONTAINER_USER}
WORKDIR ${HOME_DIR}

ENTRYPOINT ["sh", "-c", "acedd -conf=$DATA_DIR/smart.conf -datadir=$DATA_DIR"]
